# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 259d00dce3e4da9d3e143cc92492d5f39b541d03abe7e31f8d185623ac19fa2d2d7e40d97e7350525251503f8eebb3cfd5c87e28ffc021751501d9ac6100b31d

test:
  secret_key_base: 184c6221321158846a2c990838766a6fc825792cde2cd9b420c9cbe0df7fa8a602c83267307e318b8f28ede9c9c6249de5d5e0d59d3a5ff03202d1fcd8311e5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
